### ISSUE TITLE
Usage breaks import rule for Webfonts

### ISSUE THREAD

**Issue by Webling** [eschmar/css-inliner-bundle#1]
<style type="text/css">
       @import url(http://fonts.googleapis.com/css?family=Railway);
</style>

converts to an empty <style>-Tag and the import is lost.

Is there any workaround you know or do you have an idea to fix this?

**Comment by eschmar** [comment]
Sorry for the late answer, @Webling . This happens, because of the call to `$inliner->setStripOriginalStyleTags();`. Did you try placing the font rule outside of the `{% cssinline %}...{% endcssinline %}` tag?

**Comment by Webling** [comment]
Hi and thanks for your reply. Of course I tried to place the rule outside of the cssinline, but that lead to this https://github.com/eschmar/css-inliner-bundle/issues/2#issuecomment-398826722

I will update CSSToInline now and see what happens.
