### ISSUE TITLE
How to get rid of the unwanted set of Doctype?

### ISSUE THREAD

**Issue by Webling** [eschmar/css-inliner-bundle#2]
The inliner always adds a
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd"> 

When i place {% cssinline %} in the <head> I get a second Doctype within the <head>-Tag.

<img width="959" alt="wtf" src="https://user-images.githubusercontent.com/447495/41497954-2ed8ca6c-7161-11e8-904a-61774fe47ef3.png">

**Comment by eschmar** [comment]
Unfortunately, I have never had this issue, wrapping the whole document. This might have been resolved within a newer version of the [CssToInlineStyles](https://github.com/tijsverkoyen/CssToInlineStyles) library. However, right now i don't have time for an update. Open to pull requests though.

**Comment by eschmar** [comment]
This should be resolved with the latest version.
